### ISSUE TITLE
Node-Gyp build error

### ISSUE THREAD

**Issue by yaslam-dev** [uilibrary/matx-react#14]
While installing dependencies, Node-Gyp errors pops up, I have updated global node-gyp to latest version but still this errors pops up.

`npm ERR! code 1
npm ERR! path /home/yasir/Desktop/Projects/mukabir/Client/node_modules/grpc
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.1.0
npm ERR! gyp info using node@15.14.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/yasir/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/yasir/Desktop/Projects/mukabir/Client/node_modules/grpc/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/yasir/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/yasir/.cache/node-gyp/15.14.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/yasir/.cache/node-gyp/15.14.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/yasir/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/yasir/.cache/node-gyp/15.14.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/yasir/Desktop/Projects/mukabir/Client/node_modules/grpc',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/yasir/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/configure.js:353:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.8.0-55-generic
npm ERR! gyp ERR! command "/home/yasir/.nvm/versions/node/v15.14.0/bin/node" "/home/yasir/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/yasir/Desktop/Projects/mukabir/Client/node_modules/grpc
npm ERR! gyp ERR! node -v v15.14.0
npm ERR! gyp ERR! node-gyp -v v8.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yasir/.npm/_logs/2021-06-08T07_35_43_494Z-debug.log`

**Comment by JordenGershenson** [comment]
Having a similar issue. Log file attached.
[2021-06-11T20_20_25_817Z-debug.log](https://github.com/uilibrary/matx-react/files/6640814/2021-06-11T20_20_25_817Z-debug.log)

**Comment by gurusabarish** [comment]
same error here @mh-rafi . please, help me to figure out

**Comment by clratliff** [comment]
I reached out to UI Lib directly about this because I'm trying to decide if I want to purchase the pro version. Here is a snippet of the response I received:

_Hi, you are right, the free version is outdated. The Premium version has the latest version of packages. 
One thing I want to clarify, if you want to use firebase you need to use nodejs v12, because nodejs latest version can't compile firebase. Otherwise you can use latest version of nodejs._

For the gyp issues I used this as a reference (I'm on Windows):
https://spin.atomicobject.com/2019/03/27/node-gyp-windows/

Installing Python 2.7 finally resolved it for me. I had to configure Node to use that version. 

Also, note that in the response above, they mentioned Firebase not compiling unless you're using node v12. I updated the entry for firebase in package.json to reference the latest version. I was finally able to get all of the dependencies installed locally and was able to start the app. I don't plan on using firebase for authentication.

Anyway, I hope this helps in some small way to figure out the issue on your end. I really hope that UI Lib fixes the issues with this version (especially all the deprecated dependencies!). It's not helping them to attract paid users otherwise.

**Comment by gurusabarish** [comment]
@clratliff Thanks :heart:
